controller_manager:
  ros__parameters:
    update_rate: 10 # Hz

    right_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    left_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

right_arm_controller:
  ros__parameters:
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4

    command_interfaces:
      - position

    state_interfaces:
      - position
    
    open_loop_control: true
    allow_integration_in_goal_trajectories: true

left_arm_controller:
  ros__parameters:
    joints:
      - joint_5
      - joint_6
      - joint_7
      - joint_8

    command_interfaces:
      - position

    state_interfaces:
      - position

    open_loop_control: true
    allow_integration_in_goal_trajectories: true
