# Default initial positions for grizzle's ros2_control fake system

initial_positions:
  rotation 10: 0
  rotation 11: 0
  rotation 12: 0
  rotation 13: 0
  rotation 6: 0
  rotation 7: 0
  rotation 8: 0
  rotation 9: 0